// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYyDJpRHRtGfPrHm00MGCnIJ4LgsRtNiE',
    appId: '1:560944576659:web:1a1c82c76cd009e97b7566',
    messagingSenderId: '560944576659',
    projectId: 'fliq-1638d',
    authDomain: 'fliq-1638d.firebaseapp.com',
    storageBucket: 'fliq-1638d.firebasestorage.app',
    measurementId: 'G-FW025RBSW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsMfApleaIW_edXb2QH4TsV54dhbPD5SI',
    appId: '1:560944576659:android:15be224f53156a5b7b7566',
    messagingSenderId: '560944576659',
    projectId: 'fliq-1638d',
    storageBucket: 'fliq-1638d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGoD1vwP4DKoZGyp7ps-Mscd2ryOgkMPk',
    appId: '1:560944576659:ios:ffca7cfa40f4996b7b7566',
    messagingSenderId: '560944576659',
    projectId: 'fliq-1638d',
    storageBucket: 'fliq-1638d.firebasestorage.app',
    iosClientId: '560944576659-oimonijndu7u39rrk341s70rg4h5fn89.apps.googleusercontent.com',
    iosBundleId: 'com.fliq.fliq',
  );

}